### ISSUE TITLE
Test the webpage for any Vulnerabilities or bugs.

### ISSUE THREAD

**Issue by ROHITHDHARURU** [ROHITHDHARURU/project680#3]
Please fetch the latest code to ur workspace and start testing all the features currently available and raise issues to the concerned persons.

**Comment by Sujitha-04** [comment]
1. I think it looks better if we use "sign in" everywhere instead of "Login." or vice versa.
2. I think it is better to say if the email is not registered the "NOT REGISTERED" and if the incorrect credentials, then "INVALID EMAIL OR PASSWORD".
3. Title for the Signup page.
4. It's better to show the Full Name after "WELCOME" instead of emailId.
5. As professor suggested, Logics of "PREDICATE, COMBINATIONAL, ACTIVE CLAUSE COVERAGES" can be shown before performing them. And it looks better if they are presented on a separate page like "HOME PAGE" showing all details regarding this project.
6. It is better to differentiate "TRUE" and "FALSE" classes using different colors in "PREDICATE COVERAGE".
7. Need changes in "ACTIVE CLAUSE COVERAGE".
8. Better to get popup when clicking "SAVE DATA".
9. It's better to add "DELETE" option in "HISTORY"(preventing from saving same logic multiple times).

**Comment by ROHITHDHARURU** [comment]
@Sujitha-04  major issues that were raised has been fixed. Please test and if you find any critical bugs please create a new issue to track for milestone3.

**Comment by ROHITHDHARURU** [comment]
verified
